In [1]:
import pandas as pd

In [2]:
d = pd.read_csv('list.csv')
d

,Symbol,Name,Price,change,change.1,low,high,previous close
0,WMT,Walmart Inc,139.65,0.24,0.17,138.32,139.84,139.41
1,WBA,Walgreens Boots Alliance Inc,35.43,0.74,2.13,34.40,35.60,34.69
2,VZ,Verizon Communications Inc,36.35,0.38,1.06,35.80,36.43,35.97
3,V,Visa Inc,195.08,4.37,2.29,190.72,195.18,190.71
4,UNH,UnitedHealth Group Inc,537.91,-3.69,-0.68,533.90,543.92,541.60
5,TRV,Travelers Companies Inc,176.35,-3.44,-1.91,175.72,178.64,179.79
6,PG,Procter & Gamble Co,130.78,1.41,1.09,128.47,131.07,129.37
7,NKE,Nike Inc,91.74,3.73,4.24,87.89,91.93,88.01
8,MSFT,Microsoft Corp,249.73,2.48,1.00,245.83,250.11,247.25
9,MRK,Merck & Co Inc,97.99,0.62,0.64,96.35,98.29,97.37
10,MMM,3M Co,117.99,-0.39,-0.33,113.15,118.60,118.38
11,MCD,McDonald's Corp,256.65,1.33,0.52,254.40,257.28,255.32
12,KO,Coca-Cola Co,58.83,1.25,2.18,57.75,59.06,57.57
13,JPM,JPMorgan Chase & Co,122.90,0.52,0.42,120.89,123.27,122.38
14,JNJ,Johnson & Johnson,170.68,-0.30,-0.18,168.52,171.11,170.98
15,INTC,Intel Corp,27.34,0.17,0.61,27.00,27.56,27.18
16,IBM,International Business Machines Corp,132.95,0.26,0.20,131.30,133.22,132.69
17,HON,Honeywell International Inc,188.82,1.92,1.03,186.20,189.30,186.90
18,HD,Home Depot Inc,289.67,6.41,2.26,285.51,292.13,283.26
19,GS,Goldman Sachs Group Inc,331.61,2.91,0.89,325.92,332.21,328.70
20,DOW,Dow Inc,47.84,0.80,1.70,46.53,47.86,47.04
21,DIS,Walt Disney Co,104.11,2.40,2.35,102.03,104.22,101.72
22,CVX,Chevron Corp,174.23,1.10,0.64,172.17,174.97,173.13
23,CSCO,Cisco Systems Inc,44.20,0.66,1.50,43.20,44.29,43.54
24,CRM,Salesforce Inc,164.95,4.30,2.68,161.68,165.65,160.65
25,CAT,Caterpillar Inc,194.04,2.75,1.43,188.92,194.17,191.30
26,BA,Boeing Co,145.97,3.93,2.76,141.88,146.57,142.05
27,AXP,American Express Co,146.39,4.76,3.36,141.60,147.44,141.63
28,AMGN,Amgen Inc,260.32,-0.99,-0.38,257.19,261.79,261.32
29,AAPL,Apple Inc,151.96,2.51,1.68,149.36,152.05,149.45

In [3]:
k = d['Symbol']
k

0      WMT
1      WBA
2       VZ
3        V
4      UNH
5      TRV
6       PG
7      NKE
8     MSFT
9      MRK
10     MMM
11     MCD
12      KO
13     JPM
14     JNJ
15    INTC
16     IBM
17     HON
18      HD
19      GS
20     DOW
21     DIS
22     CVX
23    CSCO
24     CRM
25     CAT
26      BA
27     AXP
28    AMGN
29    AAPL
Name: Symbol, dtype: object

In [5]:
l = k.tolist()
l

['WMT',
 'WBA',
 'VZ',
 'V',
 'UNH',
 'TRV',
 'PG',
 'NKE',
 'MSFT',
 'MRK',
 'MMM',
 'MCD',
 'KO',
 'JPM',
 'JNJ',
 'INTC',
 'IBM',
 'HON',
 'HD',
 'GS',
 'DOW',
 'DIS',
 'CVX',
 'CSCO',
 'CRM',
 'CAT',
 'BA',
 'AXP',
 'AMGN',
 'AAPL']

In [6]:
 asset = ['WMT','WBA', 'VZ', 'V', 'UNH', 'TRV', 'PG', 'NKE', 'MSFT',  'MRK',  'MMM', 'MCD', 'KO', 'JPM', 'JNJ', 'INTC', 'IBM', 'HON', 'HD', 'GS', 'DOW', 'DIS', 'CVX', 'CSCO', 'CRM', 'CAT', 'BA', 'AXP', 'AMGN', 'AAPL']

In [7]:
asset

['WMT',
 'WBA',
 'VZ',
 'V',
 'UNH',
 'TRV',
 'PG',
 'NKE',
 'MSFT',
 'MRK',
 'MMM',
 'MCD',
 'KO',
 'JPM',
 'JNJ',
 'INTC',
 'IBM',
 'HON',
 'HD',
 'GS',
 'DOW',
 'DIS',
 'CVX',
 'CSCO',
 'CRM',
 'CAT',
 'BA',
 'AXP',
 'AMGN',
 'AAPL']